# This YAML file configures Travis CI to test the Spring Boot application.

language: java

jdk:
  - oraclejdk8

script:
  - mvn install

notifications:
  email:
    on_success: change
    on_failure: always
